FROM node:22-alpine AS builder

WORKDIR /app

COPY client/package*.json ./client/
RUN cd client && npm install

COPY client ./client
COPY shared ./shared

RUN cd client && npm run build

FROM nginx:alpine
COPY --from=builder /app/client/dist /usr/share/nginx/html
COPY nginx.client.conf /etc/nginx/conf.d/default.conf